/*
 * Classname: BookForm.java
 * 
 * Version 1.0
 *
 * Copyright (C) 2014 Chris
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package view;

import controller.BookShopController;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * This class contains controls and methods that effect the BookForm UI
 * @author Chris
 */
public class BookForm extends javax.swing.JFrame {

    public List publishers = new ArrayList();
    public List editData = new ArrayList();
    CardLayout cl;

    /**
     * Creates new form BookForm
     */
    public BookForm() {
        initComponents();
        cl = (CardLayout) (layerPane.getLayout());
    }

    //<editor-fold defaultstate="collapsed" desc="Form Generation and events">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        txtIsbn = new javax.swing.JTextField();
        lblIsbn = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        lblAuthors = new javax.swing.JLabel();
        txtAuthors = new javax.swing.JTextField();
        lblPubDate = new javax.swing.JLabel();
        txtPubDate = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblType = new javax.swing.JLabel();
        comboType = new javax.swing.JComboBox();
        layerPane = new javax.swing.JLayeredPane();
        panelElec = new javax.swing.JPanel();
        lblFormat = new javax.swing.JLabel();
        lblLicences = new javax.swing.JLabel();
        txtFormat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaLicences = new javax.swing.JTextArea();
        panelPaper = new javax.swing.JPanel();
        lblPostCost = new javax.swing.JLabel();
        txtPostCost = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblPrice1 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        lblPub = new javax.swing.JLabel();
        comboPub = new javax.swing.JComboBox();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Book Shop - Books");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblIsbn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIsbn.setText("ISBN");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTitle.setText("Title");

        lblAuthors.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAuthors.setText("Author(s)");

        lblPubDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPubDate.setText("Publication Date");

        lblPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPrice.setText("Price");

        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });

        lblType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblType.setText("Type");

        comboType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Electronic", "Paper" }));
        comboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTypeActionPerformed(evt);
            }
        });

        layerPane.setLayout(new java.awt.CardLayout());

        lblFormat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFormat.setText("Format");

        lblLicences.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLicences.setText("Licences");

        txtAreaLicences.setColumns(20);
        txtAreaLicences.setRows(5);
        jScrollPane1.setViewportView(txtAreaLicences);

        javax.swing.GroupLayout panelElecLayout = new javax.swing.GroupLayout(panelElec);
        panelElec.setLayout(panelElecLayout);
        panelElecLayout.setHorizontalGroup(
            panelElecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelElecLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelElecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFormat)
                    .addComponent(lblLicences))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(panelElecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(txtFormat))
                .addContainerGap())
        );
        panelElecLayout.setVerticalGroup(
            panelElecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelElecLayout.createSequentialGroup()
                .addGroup(panelElecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelElecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLicences)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layerPane.add(panelElec, "Electronic");
        layerPane.setLayer(panelElec, 1);

        lblPostCost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPostCost.setText("Postage Cost");

        javax.swing.GroupLayout panelPaperLayout = new javax.swing.GroupLayout(panelPaper);
        panelPaper.setLayout(panelPaperLayout);
        panelPaperLayout.setHorizontalGroup(
            panelPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaperLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblPostCost)
                .addGap(42, 42, 42)
                .addComponent(txtPostCost, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPaperLayout.setVerticalGroup(
            panelPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaperLayout.createSequentialGroup()
                .addGroup(panelPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPostCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPostCost))
                .addGap(0, 113, Short.MAX_VALUE))
        );

        layerPane.add(panelPaper, "Paper");
        layerPane.setLayer(panelPaper, 2);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblPrice1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPrice1.setText("Stock");

        lblPub.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPub.setText("Publisher");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(layerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrice1)
                    .addComponent(lblType)
                    .addComponent(lblPrice)
                    .addComponent(lblAuthors)
                    .addComponent(lblPubDate)
                    .addComponent(lblIsbn)
                    .addComponent(lblTitle)
                    .addComponent(lblPub))
                .addGap(29, 29, 29)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboPub, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStock)
                    .addComponent(txtPrice)
                    .addComponent(txtAuthors)
                    .addComponent(txtPubDate)
                    .addComponent(txtTitle)
                    .addComponent(comboType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIsbn))
                .addContainerGap())
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsbn)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthors)
                    .addComponent(txtAuthors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPubDate)
                    .addComponent(txtPubDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice1)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPub)
                    .addComponent(comboPub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(layerPane, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClear)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        BookShopController.closeForm("book");
    }//GEN-LAST:event_menuExitActionPerformed

    private void comboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTypeActionPerformed
        cl.show(layerPane, this.comboType.getSelectedItem().toString());
    }//GEN-LAST:event_comboTypeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (FormHelper.validateTextFields(this.jPanel)) {
            String isbn = this.txtIsbn.getText();
            String title = this.txtTitle.getText();
            String authors = this.txtAuthors.getText();
            String pubDate = this.txtPubDate.getText();
            double price = (Double.valueOf(this.txtPrice.getText()));
            String type = this.comboType.getSelectedItem().toString();
            int stock = (Integer.valueOf(this.txtStock.getText()));
            String publisher = this.comboPub.getSelectedItem().toString();

            if (type.matches("Paper")) {
                double postageCost = (Double.valueOf(this.txtPostCost.getText()));
                BookShopController.newBook(isbn, title, authors, pubDate, price,
                        postageCost, type, stock, publisher);
            } else {
                String format = this.txtFormat.getText();
                List licences = new ArrayList();
                licences.addAll(Arrays.asList(this.txtAreaLicences.getText().split("\\n")));
                BookShopController.newBook(isbn, title, authors, pubDate, price,
                        format, licences, type, stock, publisher);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        BookShopController.closeForm("book");
    }//GEN-LAST:event_formWindowClosing

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        BookShopController.closeForm("book");
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        FormHelper.clearTextFields(this.jPanel);
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
        FormHelper.checkForNumber(evt);
    }//GEN-LAST:event_txtPriceKeyTyped
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Methods for setting of form fields">

    /**
     * Sets the lists of publishers comboBox
     */
        public void setPudCombo() {
        publishers = BookShopController.listPublishers();
        for (Object name : publishers) {
            this.comboPub.addItem(name.toString());
        }
    }
    
    /**
     *  Sets all data fields to data in the editData array
     * @param type
     */
    public void setDataFields(String type) {
        this.txtIsbn.setText(editData.get(0).toString());
        this.txtTitle.setText(editData.get(1).toString());
        this.txtAuthors.setText(editData.get(2).toString());
        this.txtPubDate.setText(editData.get(3).toString());
        this.txtPrice.setText(editData.get(4).toString());
        this.txtStock.setText(editData.get(5).toString());
        this.comboPub.getModel().setSelectedItem(editData.get(6).toString());
        
        if (type.matches("Paper")) {
            this.txtPostCost.setText(editData.get(7).toString());
            this.comboType.setSelectedItem("Paper");
        } else {
            this.txtFormat.setText(editData.get(7).toString());
            for (Object l : (ArrayList) editData.get(8)) {
                this.txtAreaLicences.append(l.toString() + "\n");
            }
            this.comboType.setSelectedItem("Electronic");
        }
        
        cl.show(layerPane, type);
    }
//</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox comboPub;
    private javax.swing.JComboBox comboType;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLayeredPane layerPane;
    private javax.swing.JLabel lblAuthors;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblLicences;
    private javax.swing.JLabel lblPostCost;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPrice1;
    private javax.swing.JLabel lblPub;
    private javax.swing.JLabel lblPubDate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblType;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JPanel panelElec;
    private javax.swing.JPanel panelPaper;
    private javax.swing.JTextArea txtAreaLicences;
    private javax.swing.JTextField txtAuthors;
    private javax.swing.JTextField txtFormat;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtPostCost;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPubDate;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
